# Generated by Django 4.1 on 2022-09-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(null=True, upload_to='flags'),
        ),
        migrations.AlterField(
            model_name='country',
            name='main_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='countries', to='profile.language'),
        ),
    ]
