# Generated by Django 4.1.1 on 2022-09-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_country_flag_alter_country_main_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='profile.theme'),
        ),
    ]
