# Generated by Django 4.1.1 on 2022-09-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_account_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', to='profile.language'),
        ),
    ]
